Дипломный проект
Latarho/java-explore-with-me pull request #1
Opened 2022-10-14 20:20 UTC by Latarho

Реализована функциональность - Пользователи

2022-10-25 17:43 UTC, EvgenyKoptubenko commented on README.md
> +https://github.com/Latarho/java-explore-with-me/pull/1
Когда проект такой большой, то нужно делать документацию. В идеале ее делать через Docsify или еще какие-то инструменты, но в данном случае достаточно было бы написать в readme.md что делает этот проект и как его локально запустить.

2022-10-25 18:15 UTC, EvgenyKoptubenko commented on ewm/src/main/java/ru/practicum/ewm/repository/EventRepository.java
> +    @Query("SELECT e FROM Event AS e " +
Когда пишешь код не используй переменные длиной в 1 символ. Потом очень сложно найти где используется переменная, когда у тебя селекты будут по 2 страницы длиной.

2022-10-25 18:22 UTC, EvgenyKoptubenko commented on ewm/src/main/java/ru/practicum/ewm/service/category/CategoryServiceImpl.java
> +        Page<Category> categoryPage = categoryRepository.findAll(PageRequest.of(from / size, size));
Тут точно не может быть деления на ноль? Будь осторожен с такими делениями. Лучше добавлять проверку.

2022-10-25 18:24 UTC, EvgenyKoptubenko commented on ewm/src/main/java/ru/practicum/ewm/utils/exception/ErrorHandler.java
> +    public ApiError onCategoryNotFoundException(final CategoryNotFoundException exception) {
Выглядит так, что все NOT_FOUND можно объединить в одну функцию. Эксепшены можно написать через запятую.

2022-10-25 18:26 UTC, EvgenyKoptubenko commented on ewm/src/main/java/ru/practicum/ewm/service/event/EventServiceImpl.java
> +        if (updatedEvent.getAnnotation() != null) {
проверка Event'a дублируется в следующей функции

2022-10-25 18:33 UTC, EvgenyKoptubenko commented on stats/src/main/java/ru/practicum/stats/service/StatsServiceImpl.java
> +            } else if (isUnique && !startTime.equals(endTime)) {
Сравнивать даты через equals вряд ли удастся. Лучше использовать методы из соответствующего класса.
Но тут нужно подебажить, но скорее всего !startTime.equals(endTime) всегда true

2022-10-25 18:36 UTC, EvgenyKoptubenko requested changes
Если честно, то замечаний практически нет.
Попробуй сделать configration в Idea, чтобы по одной кнопке запускалось сразу два проекта.
Так же напиши документацию и как запускать проекты локально.
Было бы здорово так же иметь скрипт, который собирает и запускает проект локально.

2022-10-27 16:53 UTC, Latarho commented on ewm/src/main/java/ru/practicum/ewm/service/event/EventServiceImpl.java
> +        if (updatedEvent.getAnnotation() != null) {
Проверки Event'a вынесены в отдельный метод updateEventData.
В методах updateEvent и updateEventAdmin происходит вызов данного метода.

2022-10-27 16:54 UTC, Latarho commented on stats/src/main/java/ru/practicum/stats/service/StatsServiceImpl.java
> +            } else if (isUnique && !startTime.equals(endTime)) {
Реализовал сравнение объектов класса LocalDateTime с помощью метода compareTo.

2022-10-27 16:55 UTC, Latarho commented on ewm/src/main/java/ru/practicum/ewm/utils/exception/ErrorHandler.java
> +    public ApiError onCategoryNotFoundException(final CategoryNotFoundException exception) {
Агрегировал все *NotFound эксепшены в один - EntityNotFoundException.

2022-10-27 16:56 UTC, Latarho commented on ewm/src/main/java/ru/practicum/ewm/service/category/CategoryServiceImpl.java
> +        Page<Category> categoryPage = categoryRepository.findAll(PageRequest.of(from / size, size));
Реализовал проверку в классе PageBuilder.

2022-10-27 16:56 UTC, Latarho commented on ewm/src/main/java/ru/practicum/ewm/repository/EventRepository.java
> +    @Query("SELECT e FROM Event AS e " +
Спасибо за комментарий, в данной ситуации не изменял имя переменной, сделал подробный javadoc.

2022-10-27 16:56 UTC, Latarho commented on README.md
> +https://github.com/Latarho/java-explore-with-me/pull/1
Документация подготовлена.

2022-10-27 18:54 UTC, EvgenyKoptubenko reviewed
В диаграмме есть compilations_events табличка для того, чтобы убрать многое ко многим. Но в коде такой таблицы нет

2022-10-27 19:00 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо

2022-10-27 20:00 UTC, merged